### ISSUE TITLE
Start 버튼 기능 구현 - 두영

### ISSUE THREAD

**Issue by dooyeong20** [dooyeong20/git-practice-stopwatch#3]
- [x] 버튼 클릭했을 때 stop/resume 상태 변환
- [x] 버튼 클릭했을 때 시간 멈추기/다시 시작하기

**Comment by dooyeong20** [comment]
runningStatus 는 stop | running | paused로 설정하겠습니다!

**Comment by HyunJungC-Dev** [comment]
> runningStatus 는 stop | running | paused로 설정하겠습니다!
네!
