### ISSUE TITLE
Lap 버튼 기능 구현 - 현정

### ISSUE THREAD

**Issue by HyunJungC-Dev** [dooyeong20/git-practice-stopwatch#4]
- [ ]  버튼 클릭했을 때의 스톱워치 시간을 데이터 배열에 저장
- [ ]  배열에 저장된 시간들을 버튼 아래에 표시

**Comment by HyunJungC-Dev** [comment]
상태 중에 lap 배열 이름 -> const laps = [] 로 수정할께요. 
배열 전체 고차함수 돌 때 각각을 lap으로 가져오는 게 의미상 더 좋을 것 같아서요.

**Comment by ulgoon** [comment]
Assignnes에 사용자 표현이 되므로 이슈에 이름을 남기지 않으셔도 됩니다^^

**Comment by dooyeong20** [comment]
lap은 상태니까 const 보다는 let으로 선언하는게 좋지 않을까요?!

**Comment by HyunJungC-Dev** [comment]
> 넵 근데 laps같은 경우에는 상태니까 const 보다는 let으로 선언하는게 좋지 않을까요?!

재할당해줄거니 맞네요!  수정하겠습니다!

**Comment by dooyeong20** [comment]
현정님 그리고 지금 측정 시작 안했을 때도 lap이 찍히는데, 상태 확인해서 running일때만 lap 찍힐 수 있도록 해주실 수 있나요!

**Comment by HyunJungC-Dev** [comment]
네 안 그래도 그 이슈 작성하려했는데 추가하겠습니다!!
