### ISSUE TITLE
Reset 버튼 기능 구현 

### ISSUE THREAD

**Issue by dooyeong20** [dooyeong20/git-practice-stopwatch#5]
- [x] html 초기화
- [x] 상태 초기화

**Comment by ulgoon** [comment]
관련 pull request나 commit 과 referencing이 되면 좋을 것 같아요^^ 커밋 당시에 해야할걸 놓쳤다면, 해당 커밋의 댓글로 연결하실 수 있습니다^^

**Comment by dooyeong20** [comment]
> 관련 pull request나 commit 과 referencing이 되면 좋을 것 같아요^^ 커밋 당시에 해야할걸 놓쳤다면, 해당 커밋의 댓글로 연결하실 수 있습니다^^

넵! 근데 이게 제 레포라서 제가 push 하면 pull request 없이 바로 develop 브랜치에 적용되는데, 그럴 경우에는 referencing을 어떻게 하나요..?

**Comment by ulgoon** [comment]
> > 관련 pull request나 commit 과 referencing이 되면 좋을 것 같아요^^ 커밋 당시에 해야할걸 놓쳤다면, 해당 커밋의 댓글로 연결하실 수 있습니다^^
> 
> 넵! 근데 이게 제 레포라서 제가 push 하면 pull request 없이 바로 develop 브랜치에 적용되는데, 그럴 경우에는 referencing을 어떻게 하나요..?

referencing 자체는 이슈넘버와 prefix만 달아주면 동작하므로 pull request와는 관련이 없습니다.
그래서 커밋하실 때 referencing 하시면 됩니다.

만약 내가 repo 주인인데 나도 pull request를 하고 싶다 라고 하신다면
feature 브랜치에서 push 후 develop 브랜치로 pull request 를 날리시면 됩니다

**Comment by dooyeong20** [comment]
> > > 관련 pull request나 commit 과 referencing이 되면 좋을 것 같아요^^ 커밋 당시에 해야할걸 놓쳤다면, 해당 커밋의 댓글로 연결하실 수 있습니다^^
> > 
> > 
> > 넵! 근데 이게 제 레포라서 제가 push 하면 pull request 없이 바로 develop 브랜치에 적용되는데, 그럴 경우에는 referencing을 어떻게 하나요..?
> 
> referencing 자체는 이슈넘버와 prefix만 달아주면 동작하므로 pull request와는 관련이 없습니다.
> 그래서 커밋하실 때 referencing 하시면 됩니다.
> 
> 만약 내가 repo 주인인데 나도 pull request를 하고 싶다 라고 하신다면
> feature 브랜치에서 push 후 develop 브랜치로 pull request 를 날리시면 됩니다

오호 감사합니다! 다음부터 커밋할 때 referencing 할게요!
